import { JSONContent } from '@tiptap/core';
import { v4 as uuidv4 } from 'uuid';

/**
 * Generates a comprehensive boilerplate template with:
 * - All built-in extensions (headings, paragraphs, lists, etc.)
 * - All custom nodes with their latest structure and attributes
 * - All variants and functionalities for each custom node
 * - Approval Required feature examples
 * - Query parameter pre-population examples
 * - Visibility conditions examples
 * - Node grouping examples
 * - Real-world use cases
 */
export function generateFormBuilderBoilerplate(): JSONContent {
  return {
    type: 'doc',
    content: [
      // ── HEADING ─────────────────────────────────────
      {
        type: 'heading',
        attrs: { level: 1 },
        content: [{ type: 'text', text: 'Form Builder Boilerplate' }],
      },
      {
        type: 'paragraph',
        content: [
          {
            type: 'text',
            text: 'This template includes all enabled extensions and custom nodes with their latest structure, variants, and functionalities.',
          },
        ],
      },
      {
        type: 'horizontalRule',
      },

      // ── BUILT-IN EXTENSIONS ────────────────────────
      {
        type: 'heading',
        attrs: { level: 2 },
        content: [{ type: 'text', text: 'Built-in Extensions' }],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Heading 3 Example' }],
      },
      {
        type: 'heading',
        attrs: { level: 4 },
        content: [{ type: 'text', text: 'Heading 4 Example' }],
      },
      {
        type: 'paragraph',
        content: [
          { type: 'text', text: 'This is a ' },
          { type: 'text', marks: [{ type: 'bold' }], text: 'bold' },
          { type: 'text', text: ' and ' },
          { type: 'text', marks: [{ type: 'italic' }], text: 'italic' },
          { type: 'text', text: ' text example with ' },
          { type: 'text', marks: [{ type: 'code' }], text: 'code' },
          { type: 'text', text: ' and ' },
          {
            type: 'text',
            marks: [{ type: 'highlight', attrs: { color: '#fef08a' } }],
            text: 'highlighted',
          },
          { type: 'text', text: ' text.' },
        ],
      },
      {
        type: 'blockquote',
        content: [
          {
            type: 'paragraph',
            content: [
              {
                type: 'text',
                text: 'This is a blockquote example.',
              },
            ],
          },
        ],
      },
      {
        type: 'codeBlock',
        attrs: { language: 'javascript' },
        content: [
          {
            type: 'text',
            text: 'const example = "code block";\nconsole.log(example);',
          },
        ],
      },
      {
        type: 'horizontalRule',
      },

      // ── SHORT TEXT VARIANTS ────────────────────────
      {
        type: 'heading',
        attrs: { level: 2 },
        content: [{ type: 'text', text: 'Short Text Field Variants' }],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Short Text - Text Variant' }],
      },
      {
        type: 'shortText',
        attrs: {
          id: uuidv4(),
          variant: 'text',
          name: 'short_text_basic',
          placeholder: 'Enter text...',
          required: false,
          value: '',
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Short Text - Text Variant' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Short Text - Email Variant (Required)' }],
      },
      {
        type: 'shortText',
        attrs: {
          id: uuidv4(),
          variant: 'email',
          name: 'short_text_email',
          placeholder: 'Enter email address...',
          required: true,
          value: '',
          queryParam: 'email',
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Email Address (Required)' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Short Text - Name Variant (with Prefix, Middle, Suffix)' }],
      },
      {
        type: 'shortText',
        attrs: {
          id: uuidv4(),
          variant: 'name',
          name: 'short_text_name',
          placeholder: 'Enter full name...',
          required: true,
          namePrefix: true,
          nameSuffix: true,
          middleName: true,
          namePrefixRequired: false,
          nameSuffixRequired: false,
          middleNameRequired: false,
          value: '',
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Full Name (with Prefix, Middle, Suffix)' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Short Text - Phone Variant' }],
      },
      {
        type: 'shortText',
        attrs: {
          id: uuidv4(),
          variant: 'phone',
          name: 'short_text_phone',
          placeholder: 'Enter phone number...',
          required: false,
          phoneCountryIsoCode: 'US',
          value: '',
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Phone Number' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Short Text - With Approval Required' }],
      },
      {
        type: 'shortText',
        attrs: {
          id: uuidv4(),
          variant: 'text',
          name: 'short_text_approval',
          placeholder: 'Enter value...',
          required: false,
          approvalRequired: true,
          approvalStatus: null,
          approvers: null,
          rejectionMessage: null,
          value: '',
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Short Text - With Approval Required' }],
          },
        ],
      },
      {
        type: 'horizontalRule',
      },

      // ── LONG TEXT VARIANTS ──────────────────────────
      {
        type: 'heading',
        attrs: { level: 2 },
        content: [{ type: 'text', text: 'Long Text Field Variants' }],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Long Text - Plain Text' }],
      },
      {
        type: 'longText',
        attrs: {
          id: uuidv4(),
          label: 'Long Text - Plain Text',
          name: 'long_text_plain',
          placeholder: 'Enter longer text…',
          value: '',
          minLength: 0,
          maxLength: 1000,
          regex: null,
          requiredKeywords: [],
          requiredKeywordsMode: 'all',
          required: false,
          enableRichText: false,
          approvalRequired: false,
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Long Text - Plain Text' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Long Text - With Approval Required' }],
      },
      {
        type: 'longText',
        attrs: {
          id: uuidv4(),
          label: 'Long Text - With Approval Required',
          name: 'long_text_approval',
          placeholder: 'Enter longer text…',
          value: '',
          minLength: 0,
          maxLength: 1000,
          regex: null,
          requiredKeywords: [],
          requiredKeywordsMode: 'all',
          required: false,
          enableRichText: false,
          approvalRequired: true,
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Long Text - With Approval Required' }],
          },
        ],
      },
      {
        type: 'horizontalRule',
      },

      // ── RICH TEXT ──────────────────────────────────
      {
        type: 'heading',
        attrs: { level: 2 },
        content: [{ type: 'text', text: 'Rich Text Field' }],
      },
      {
        type: 'richText',
        attrs: {
          id: uuidv4(),
          label: 'Rich Text Field',
          name: 'rich_text_field',
          value: '<p>This is a rich text editor field. You can format text with <strong>bold</strong>, <em>italic</em>, and other formatting options.</p>',
          maxLength: null,
          required: false,
          approvalRequired: false,
          queryParam: null,
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Rich Text Field' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Rich Text - With Approval Required' }],
      },
      {
        type: 'richText',
        attrs: {
          id: uuidv4(),
          label: 'Rich Text - With Approval Required',
          name: 'rich_text_approval',
          value: '<p>This field requires approval before the value is accepted.</p>',
          maxLength: null,
          required: false,
          approvalRequired: true,
          queryParam: null,
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Rich Text - With Approval Required' }],
          },
        ],
      },
      {
        type: 'horizontalRule',
      },

      // ── SINGLE CHOICE VARIANTS ──────────────────────
      {
        type: 'heading',
        attrs: { level: 2 },
        content: [{ type: 'text', text: 'Single Choice Field Variants' }],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Single Choice - Radio (Horizontal)' }],
      },
      {
        type: 'singleChoice',
        attrs: {
          id: uuidv4(),
          name: 'single_choice_radio_horizontal',
          variant: 'radio',
          layout: 'horizontal',
          randomize: false,
          defaultValue: null,
          value: null,
          allowOther: false,
          otherPlaceholder: 'Other…',
          required: false,
          approvalRequired: false,
          enablePassFail: false,
          enablePoints: false,
          failCritical: false,
          enableCalculation: false,
          optionPoints: {},
          optionLimits: {},
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Single Choice - Radio (Horizontal)' }],
          },
          {
            type: 'singleChoiceOption',
            attrs: {
              value: 'Option 1',
              imageUrl: null,
              isCorrect: false,
            },
            content: [{ type: 'text', text: 'Option 1' }],
          },
          {
            type: 'singleChoiceOption',
            attrs: {
              value: 'Option 2',
              imageUrl: null,
              isCorrect: false,
            },
            content: [{ type: 'text', text: 'Option 2' }],
          },
          {
            type: 'singleChoiceOption',
            attrs: {
              value: 'Option 3',
              imageUrl: null,
              isCorrect: false,
            },
            content: [{ type: 'text', text: 'Option 3' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Single Choice - Dropdown' }],
      },
      {
        type: 'singleChoice',
        attrs: {
          id: uuidv4(),
          name: 'single_choice_dropdown',
          variant: 'dropdown',
          layout: 'horizontal',
          randomize: false,
          defaultValue: null,
          value: null,
          allowOther: false,
          otherPlaceholder: 'Other…',
          required: false,
          approvalRequired: false,
          enablePassFail: false,
          enablePoints: false,
          failCritical: false,
          enableCalculation: false,
          optionPoints: {},
          optionLimits: {},
          queryParam: 'choice',
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Single Choice - Dropdown' }],
          },
          {
            type: 'singleChoiceOption',
            attrs: {
              value: 'Choice 1',
              imageUrl: null,
              isCorrect: false,
            },
            content: [{ type: 'text', text: 'Choice 1' }],
          },
          {
            type: 'singleChoiceOption',
            attrs: {
              value: 'Choice 2',
              imageUrl: null,
              isCorrect: false,
            },
            content: [{ type: 'text', text: 'Choice 2' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Single Choice - Yes/No' }],
      },
      {
        type: 'singleChoice',
        attrs: {
          id: uuidv4(),
          name: 'single_choice_yesno',
          variant: 'yesno',
          layout: 'horizontal',
          randomize: false,
          defaultValue: null,
          value: null,
          allowOther: false,
          otherPlaceholder: 'Other…',
          required: false,
          approvalRequired: false,
          enablePassFail: false,
          enablePoints: false,
          failCritical: false,
          enableCalculation: false,
          optionPoints: {},
          optionLimits: {},
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Single Choice - Yes/No' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Single Choice - With Other Option' }],
      },
      {
        type: 'singleChoice',
        attrs: {
          id: uuidv4(),
          name: 'single_choice_with_other',
          variant: 'radio',
          layout: 'horizontal',
          randomize: false,
          defaultValue: null,
          value: null,
          allowOther: true,
          otherPlaceholder: 'Other (please specify)…',
          required: false,
          approvalRequired: false,
          enablePassFail: false,
          enablePoints: false,
          failCritical: false,
          enableCalculation: false,
          optionPoints: {},
          optionLimits: {},
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Single Choice - With Other Option' }],
          },
          {
            type: 'singleChoiceOption',
            attrs: {
              value: 'Option 1',
              imageUrl: null,
              isCorrect: false,
            },
            content: [{ type: 'text', text: 'Option 1' }],
          },
          {
            type: 'singleChoiceOption',
            attrs: {
              value: 'Option 2',
              imageUrl: null,
              isCorrect: false,
            },
            content: [{ type: 'text', text: 'Option 2' }],
          },
          {
            type: 'singleChoiceOther',
            attrs: { isCorrect: false },
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Single Choice - With Points & Pass/Fail' }],
      },
      {
        type: 'singleChoice',
        attrs: {
          id: uuidv4(),
          name: 'single_choice_points_pf',
          variant: 'radio',
          layout: 'horizontal',
          randomize: false,
          defaultValue: null,
          value: null,
          allowOther: false,
          otherPlaceholder: 'Other…',
          required: false,
          approvalRequired: false,
          enablePassFail: true,
          enablePoints: true,
          failCritical: false,
          enableCalculation: false,
          optionPoints: {
            'Option 1': { points: 10, isCorrect: true },
            'Option 2': { points: 0, isCorrect: false },
            'Option 3': { points: 5, isCorrect: false },
          },
          optionLimits: {},
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Single Choice - With Points & Pass/Fail' }],
          },
          {
            type: 'singleChoiceOption',
            attrs: {
              value: 'Option 1',
              imageUrl: null,
              isCorrect: true,
            },
            content: [{ type: 'text', text: 'Option 1 (Correct, 10 pts)' }],
          },
          {
            type: 'singleChoiceOption',
            attrs: {
              value: 'Option 2',
              imageUrl: null,
              isCorrect: false,
            },
            content: [{ type: 'text', text: 'Option 2 (Incorrect, 0 pts)' }],
          },
          {
            type: 'singleChoiceOption',
            attrs: {
              value: 'Option 3',
              imageUrl: null,
              isCorrect: false,
            },
            content: [{ type: 'text', text: 'Option 3 (Partial, 5 pts)' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Single Choice - With Approval Required' }],
      },
      {
        type: 'singleChoice',
        attrs: {
          id: uuidv4(),
          name: 'single_choice_approval',
          variant: 'radio',
          layout: 'horizontal',
          randomize: false,
          defaultValue: null,
          value: null,
          allowOther: false,
          otherPlaceholder: 'Other…',
          required: false,
          approvalRequired: true,
          enablePassFail: false,
          enablePoints: false,
          failCritical: false,
          enableCalculation: false,
          optionPoints: {},
          optionLimits: {},
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Single Choice - With Approval Required' }],
          },
          {
            type: 'singleChoiceOption',
            attrs: {
              value: 'Option 1',
              imageUrl: null,
              isCorrect: false,
            },
            content: [{ type: 'text', text: 'Option 1' }],
          },
          {
            type: 'singleChoiceOption',
            attrs: {
              value: 'Option 2',
              imageUrl: null,
              isCorrect: false,
            },
            content: [{ type: 'text', text: 'Option 2' }],
          },
        ],
      },
      {
        type: 'horizontalRule',
      },

      // ── MULTIPLE CHOICE VARIANTS ────────────────────
      {
        type: 'heading',
        attrs: { level: 2 },
        content: [{ type: 'text', text: 'Multiple Choice Field Variants' }],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Multiple Choice - Checkbox (Horizontal)' }],
      },
      {
        type: 'multipleChoice',
        attrs: {
          id: uuidv4(),
          name: 'multiple_choice_checkbox_horizontal',
          label: 'Multiple Choice - Checkbox (Horizontal)',
          variant: 'checkbox',
          layout: 'horizontal',
          randomize: false,
          defaultValue: [],
          value: [],
          allowOther: false,
          otherPlaceholder: 'Other…',
          required: false,
          approvalRequired: false,
          enablePassFail: false,
          enablePoints: false,
          failCritical: false,
          enableCalculation: false,
          optionPoints: {},
          optionLimits: {},
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Multiple Choice - Checkbox (Horizontal)' }],
          },
          {
            type: 'multipleChoiceOption',
            attrs: {
              value: 'Option 1',
              imageUrl: null,
              isCorrect: false,
            },
            content: [{ type: 'text', text: 'Option 1' }],
          },
          {
            type: 'multipleChoiceOption',
            attrs: {
              value: 'Option 2',
              imageUrl: null,
              isCorrect: false,
            },
            content: [{ type: 'text', text: 'Option 2' }],
          },
          {
            type: 'multipleChoiceOption',
            attrs: {
              value: 'Option 3',
              imageUrl: null,
              isCorrect: false,
            },
            content: [{ type: 'text', text: 'Option 3' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Multiple Choice - With Points & Pass/Fail' }],
      },
      {
        type: 'multipleChoice',
        attrs: {
          id: uuidv4(),
          name: 'multiple_choice_points_pf',
          label: 'Multiple Choice - With Points & Pass/Fail',
          variant: 'checkbox',
          layout: 'horizontal',
          randomize: false,
          defaultValue: [],
          value: [],
          allowOther: false,
          otherPlaceholder: 'Other…',
          required: false,
          approvalRequired: false,
          enablePassFail: true,
          enablePoints: true,
          failCritical: false,
          enableCalculation: false,
          optionPoints: {
            'Option 1': { points: 10, isCorrect: true },
            'Option 2': { points: 5, isCorrect: true },
            'Option 3': { points: 0, isCorrect: false },
          },
          optionLimits: {},
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Multiple Choice - With Points & Pass/Fail' }],
          },
          {
            type: 'multipleChoiceOption',
            attrs: {
              value: 'Option 1',
              imageUrl: null,
              isCorrect: true,
            },
            content: [{ type: 'text', text: 'Option 1 (Correct, 10 pts)' }],
          },
          {
            type: 'multipleChoiceOption',
            attrs: {
              value: 'Option 2',
              imageUrl: null,
              isCorrect: true,
            },
            content: [{ type: 'text', text: 'Option 2 (Correct, 5 pts)' }],
          },
          {
            type: 'multipleChoiceOption',
            attrs: {
              value: 'Option 3',
              imageUrl: null,
              isCorrect: false,
            },
            content: [{ type: 'text', text: 'Option 3 (Incorrect, 0 pts)' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Multiple Choice - With Approval Required' }],
      },
      {
        type: 'multipleChoice',
        attrs: {
          id: uuidv4(),
          name: 'multiple_choice_approval',
          label: 'Multiple Choice - With Approval Required',
          variant: 'checkbox',
          layout: 'horizontal',
          randomize: false,
          defaultValue: [],
          value: [],
          allowOther: false,
          otherPlaceholder: 'Other…',
          required: false,
          approvalRequired: true,
          enablePassFail: false,
          enablePoints: false,
          failCritical: false,
          enableCalculation: false,
          optionPoints: {},
          optionLimits: {},
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Multiple Choice - With Approval Required' }],
          },
          {
            type: 'multipleChoiceOption',
            attrs: {
              value: 'Option 1',
              imageUrl: null,
              isCorrect: false,
            },
            content: [{ type: 'text', text: 'Option 1' }],
          },
          {
            type: 'multipleChoiceOption',
            attrs: {
              value: 'Option 2',
              imageUrl: null,
              isCorrect: false,
            },
            content: [{ type: 'text', text: 'Option 2' }],
          },
        ],
      },
      {
        type: 'horizontalRule',
      },

      // ── NUMBER FIELD VARIANTS ────────────────────────
      {
        type: 'heading',
        attrs: { level: 2 },
        content: [{ type: 'text', text: 'Number Field Variants' }],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Number - Basic (Age)' }],
      },
      {
        type: 'numberField',
        attrs: {
          id: uuidv4(),
          label: 'Age',
          name: 'number_age',
          placeholder: 'Enter your age',
          min: 0,
          max: 120,
          step: 1,
          unit: 'years',
          value: null,
          required: false,
          calculable: false,
          prefix: '',
          suffix: '',
          numberFormat: 'none',
          rounding: null,
          approvalRequired: false,
          queryParam: null,
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Age' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Number - Currency (Price)' }],
      },
      {
        type: 'numberField',
        attrs: {
          id: uuidv4(),
          label: 'Price',
          name: 'number_price',
          placeholder: '0.00',
          min: 0,
          max: 10000,
          step: 0.01,
          unit: '',
          value: null,
          required: true,
          calculable: true,
          prefix: '$',
          suffix: '',
          numberFormat: 'comma',
          rounding: 2,
          approvalRequired: false,
          queryParam: 'price',
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Price' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Number - With Approval Required' }],
      },
      {
        type: 'numberField',
        attrs: {
          id: uuidv4(),
          label: 'Amount (Requires Approval)',
          name: 'number_amount_approval',
          placeholder: '0.00',
          min: 0,
          max: 1000000,
          step: 0.01,
          unit: '',
          value: null,
          required: false,
          approvalRequired: true,
          calculable: false,
          prefix: '$',
          suffix: '',
          numberFormat: 'comma',
          rounding: 2,
          queryParam: null,
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Amount (Requires Approval)' }],
          },
        ],
      },
      {
        type: 'horizontalRule',
      },

      // ── SLIDER FIELD VARIANTS ────────────────────────
      {
        type: 'heading',
        attrs: { level: 2 },
        content: [{ type: 'text', text: 'Slider Field Variants' }],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Slider - Basic (Satisfaction 0-10)' }],
      },
      {
        type: 'sliderField',
        attrs: {
          id: uuidv4(),
          label: 'Satisfaction Level',
          name: 'slider_satisfaction',
          min: 0,
          max: 10,
          step: 1,
          rangeMode: false,
          marks: undefined,
          value: undefined,
          showTicks: true,
          required: false,
          approvalRequired: false,
          displayValue: 'tooltip',
          displayStepValues: 'minmax',
          prefix: '',
          suffix: '',
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Satisfaction Level' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Slider - Range (Budget Range)' }],
      },
      {
        type: 'sliderField',
        attrs: {
          id: uuidv4(),
          label: 'Budget Range',
          name: 'slider_budget_range',
          min: 0,
          max: 1000,
          step: 100,
          rangeMode: true,
          marks: {
            0: '$0',
            250: '$250',
            500: '$500',
            750: '$750',
            1000: '$1000',
          },
          value: undefined,
          showTicks: true,
          required: false,
          approvalRequired: false,
          displayValue: 'above',
          displayStepValues: 'all',
          prefix: '$',
          suffix: '',
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Budget Range' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Slider - With Approval Required' }],
      },
      {
        type: 'sliderField',
        attrs: {
          id: uuidv4(),
          label: 'Priority Level (Requires Approval)',
          name: 'slider_priority_approval',
          min: 1,
          max: 10,
          step: 1,
          rangeMode: false,
          marks: undefined,
          value: undefined,
          showTicks: true,
          required: false,
          approvalRequired: true,
          displayValue: 'tooltip',
          displayStepValues: 'minmax',
          prefix: '',
          suffix: '',
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Priority Level (Requires Approval)' }],
          },
        ],
      },
      {
        type: 'horizontalRule',
      },

      // ── RATING FIELD VARIANTS ─────────────────────────
      {
        type: 'heading',
        attrs: { level: 2 },
        content: [{ type: 'text', text: 'Rating Field Variants' }],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Rating - Stars (5 Star)' }],
      },
      {
        type: 'ratingField',
        attrs: {
          id: uuidv4(),
          label: 'Overall Rating',
          name: 'rating_overall',
          variant: 'stars',
          scale: 5,
          allowHalf: false,
          anchorLabels: undefined,
          value: null,
          required: false,
          approvalRequired: false,
          showSuffix: false,
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Overall Rating' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Rating - Anchors (with Labels)' }],
      },
      {
        type: 'ratingField',
        attrs: {
          id: uuidv4(),
          label: 'Performance Rating',
          name: 'rating_performance',
          variant: 'anchors',
          scale: 5,
          allowHalf: false,
          anchorLabels: ['Poor', 'Fair', 'Good', 'Very Good', 'Excellent'],
          value: null,
          required: true,
          approvalRequired: false,
          showSuffix: false,
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Performance Rating' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Rating - With Approval Required' }],
      },
      {
        type: 'ratingField',
        attrs: {
          id: uuidv4(),
          label: 'Performance Rating (Requires Approval)',
          name: 'rating_approval',
          variant: 'stars',
          scale: 5,
          allowHalf: false,
          anchorLabels: undefined,
          value: null,
          required: false,
          approvalRequired: true,
          showSuffix: false,
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Performance Rating (Requires Approval)' }],
          },
        ],
      },
      {
        type: 'horizontalRule',
      },

      // ── DATE FIELD VARIANTS ───────────────────────────
      {
        type: 'heading',
        attrs: { level: 2 },
        content: [{ type: 'text', text: 'Date Field Variants' }],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Date - Basic (Birth Date)' }],
      },
      {
        type: 'dateField',
        attrs: {
          id: uuidv4(),
          label: 'Date of Birth',
          name: 'date_birth',
          placeholder: 'Select date',
          value: null,
          min: null,
          max: null,
          notInFuture: true,
          notInPast: false,
          defaultDate: 'none',
          dateFormat: 'MM-DD-YYYY',
          disabledDates: [],
          required: true,
          approvalRequired: false,
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Date of Birth' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Date - Appointment (Future Only)' }],
      },
      {
        type: 'dateField',
        attrs: {
          id: uuidv4(),
          label: 'Appointment Date',
          name: 'date_appointment',
          placeholder: 'Select appointment date',
          value: null,
          min: null,
          max: null,
          notInFuture: false,
          notInPast: true,
          defaultDate: 'today',
          dateFormat: 'MM-DD-YYYY',
          disabledDates: [],
          required: true,
          approvalRequired: false,
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Appointment Date' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Date - With Approval Required' }],
      },
      {
        type: 'dateField',
        attrs: {
          id: uuidv4(),
          label: 'Approval Date (Requires Approval)',
          name: 'date_approval',
          placeholder: 'Select date',
          value: null,
          min: null,
          max: null,
          notInFuture: false,
          notInPast: false,
          defaultDate: 'none',
          dateFormat: 'MM-DD-YYYY',
          disabledDates: [],
          required: false,
          approvalRequired: true,
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Approval Date (Requires Approval)' }],
          },
        ],
      },
      {
        type: 'horizontalRule',
      },

      // ── DATE & TIME FIELD VARIANTS ────────────────────
      {
        type: 'heading',
        attrs: { level: 2 },
        content: [{ type: 'text', text: 'Date & Time Field Variants' }],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Date & Time - Basic (24-hour)' }],
      },
      {
        type: 'dateTimeField',
        attrs: {
          id: uuidv4(),
          label: 'Meeting Date & Time',
          name: 'datetime_meeting',
          value: null,
          min: null,
          max: null,
          notInFuture: false,
          notInPast: true,
          timeFormat: '24',
          showSeconds: false,
          timezone: null,
          timeIncrement: null,
          timeLimits: null,
          required: true,
          approvalRequired: false,
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Meeting Date & Time' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Date & Time - 12-hour Format' }],
      },
      {
        type: 'dateTimeField',
        attrs: {
          id: uuidv4(),
          label: 'Appointment Date & Time',
          name: 'datetime_appointment',
          value: null,
          min: null,
          max: null,
          notInFuture: false,
          notInPast: true,
          timeFormat: '12',
          showSeconds: false,
          timezone: null,
          timeIncrement: 15,
          timeLimits: null,
          required: true,
          approvalRequired: false,
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Appointment Date & Time' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Date & Time - Business Hours (9 AM - 5 PM)' }],
      },
      {
        type: 'dateTimeField',
        attrs: {
          id: uuidv4(),
          label: 'Preferred Contact Time',
          name: 'datetime_contact',
          value: null,
          min: null,
          max: null,
          notInFuture: false,
          notInPast: false,
          timeFormat: '12',
          showSeconds: false,
          timezone: null,
          timeIncrement: 30,
          timeLimits: { start: '09:00', end: '17:00' },
          required: false,
          approvalRequired: false,
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Preferred Contact Time' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Date & Time - With Approval Required' }],
      },
      {
        type: 'dateTimeField',
        attrs: {
          id: uuidv4(),
          label: 'Event Date & Time (Requires Approval)',
          name: 'datetime_approval',
          value: null,
          min: null,
          max: null,
          notInFuture: false,
          notInPast: false,
          timeFormat: '24',
          showSeconds: false,
          timezone: null,
          timeIncrement: null,
          timeLimits: null,
          required: false,
          approvalRequired: true,
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Event Date & Time (Requires Approval)' }],
          },
        ],
      },
      {
        type: 'horizontalRule',
      },

      // ── ADDRESS FIELD VARIANTS ────────────────────────
      {
        type: 'heading',
        attrs: { level: 2 },
        content: [{ type: 'text', text: 'Address Field Variants' }],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Address - Full Address (All Fields)' }],
      },
      {
        type: 'addressField',
        attrs: {
          id: uuidv4(),
          label: 'Mailing Address',
          name: 'address_mailing',
          street: '',
          apartment: '',
          city: '',
          state: '',
          postalCode: '',
          country: '',
          formatted: '',
          lat: null,
          lng: null,
          mapEnabled: false,
          enabledFields: {
            street: true,
            apartment: true,
            city: true,
            state: true,
            postalCode: true,
            country: true,
          },
          required: true,
          approvalRequired: false,
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Mailing Address' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Address - Simplified (Street, City, Country)' }],
      },
      {
        type: 'addressField',
        attrs: {
          id: uuidv4(),
          label: 'Location',
          name: 'address_location',
          street: '',
          apartment: '',
          city: '',
          state: '',
          postalCode: '',
          country: '',
          formatted: '',
          lat: null,
          lng: null,
          mapEnabled: false,
          enabledFields: {
            street: true,
            apartment: false,
            city: true,
            state: false,
            postalCode: false,
            country: true,
          },
          required: false,
          approvalRequired: false,
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Location' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Address - With Approval Required' }],
      },
      {
        type: 'addressField',
        attrs: {
          id: uuidv4(),
          label: 'Delivery Address (Requires Approval)',
          name: 'address_delivery_approval',
          street: '',
          apartment: '',
          city: '',
          state: '',
          postalCode: '',
          country: '',
          formatted: '',
          lat: null,
          lng: null,
          mapEnabled: false,
          enabledFields: {
            street: true,
            apartment: true,
            city: true,
            state: true,
            postalCode: true,
            country: true,
          },
          required: false,
          approvalRequired: true,
          queryParam: null,
          visibility: { match: 'all', rules: [] },
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Delivery Address (Requires Approval)' }],
          },
        ],
      },
      {
        type: 'horizontalRule',
      },

      // ── RANKING FIELD VARIANTS ────────────────────────
      {
        type: 'heading',
        attrs: { level: 2 },
        content: [{ type: 'text', text: 'Ranking Field Variants' }],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Ranking - Drag & Drop (Priorities)' }],
      },
      {
        type: 'ranking',
        attrs: {
          id: uuidv4(),
          label: 'Ranking',
          name: 'ranking_priorities',
          options: ['Option A', 'Option B', 'Option C'],
          order: ['Option A-0', 'Option B-1', 'Option C-2'],
          mode: 'drag',
          iconStyle: 'star',
          emoji: '⭐',
          showSuffix: false,
          suffixText: '(0/3)',
          approvalRequired: false,
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Rank your priorities' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Ranking - Numeric (Skills Assessment)' }],
      },
      {
        type: 'ranking',
        attrs: {
          id: uuidv4(),
          label: 'Ranking',
          name: 'ranking_skills',
          options: ['Communication', 'Problem Solving', 'Teamwork', 'Leadership', 'Technical Skills'],
          order: ['Communication-0', 'Problem Solving-1', 'Teamwork-2', 'Leadership-3', 'Technical Skills-4'],
          mode: 'numeric',
          iconStyle: 'star',
          emoji: '⭐',
          showSuffix: true,
          suffixText: '(0/5)',
          approvalRequired: false,
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Rank your skills (1 = highest priority)' }],
          },
        ],
      },
      {
        type: 'heading',
        attrs: { level: 3 },
        content: [{ type: 'text', text: 'Ranking - With Approval Required' }],
      },
      {
        type: 'ranking',
        attrs: {
          id: uuidv4(),
          label: 'Ranking',
          name: 'ranking_approval',
          options: ['Priority 1', 'Priority 2', 'Priority 3'],
          order: ['Priority 1-0', 'Priority 2-1', 'Priority 3-2'],
          mode: 'drag',
          iconStyle: 'star',
          emoji: '⭐',
          showSuffix: false,
          suffixText: '(0/3)',
          approvalRequired: true,
          enableGrouping: false,
          nodeGroups: [],
          nodeGroupValues: {},
          nodeGroupApprovalStatus: {},
        },
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'Rank priorities (Requires Approval)' }],
          },
        ],
      },

    ],
  };
}
