import { RouterProvider } from 'react-router-dom';
import { ConfigProvider, theme as antdTheme } from 'antd';
import { useEffect, useRef } from 'react';

import { HelmetProvider } from 'react-helmet-async';
import { StylesContext } from './context';
import { SocketProvider } from './context/SocketContext';
import { PermissionNotification } from './components/PermissionNotification';
import { ImpersonationBanner } from './components/ImpersonationBanner';
import { SuspendedOrgBanner } from './components/SuspendedOrgBanner';
import routes from './routes/routes.tsx';
import { useSelector } from 'react-redux';
import { RootState } from './store.ts';
import { useLazyGetUserInfoQuery } from './services/authApi';
import './App.css';

// color palettes: triadic #A1A7CB, #CBA1A7, #A7CBA1
// 10 color objects of primary #2378c3 as generated by https://smart-swatch.netlify.app/#2378c3
// This is for reference purposes

export const COLOR = {
  50: '#e0f1ff',
  100: '#b0d2ff',
  200: '#7fb0ff',
  300: '#4d8bff',
  400: '#1e79fe',
  500: '#076ee5',
  600: '#0062b3',
  700: '#004f81',
  800: '#003650',
  900: '#001620',
  borderColor: '#E7EAF3B2',
};

function App() {
  const { mytheme } = useSelector((state: RootState) => state.theme);
  const [getUserInfo] = useLazyGetUserInfoQuery();
  const hasFetchedOnMount = useRef(false);

  // Set data-theme attribute on document element for CSS selectors
  useEffect(() => {
    document.documentElement.setAttribute('data-theme', mytheme);
  }, [mytheme]);

  // Fetch user info on app initialization/page refresh if tokens exist
  // This ensures we always have the latest user and profile data
  useEffect(() => {
    // Only fetch once on mount
    if (hasFetchedOnMount.current) return;
    
    // Check localStorage directly for immediate availability (works before Redux rehydration)
    const hasAccessToken = localStorage.getItem('accessToken');
    const hasRefreshToken = localStorage.getItem('refreshToken');
    
    if (hasAccessToken || hasRefreshToken) {
      hasFetchedOnMount.current = true;
      getUserInfo()
        .then((result) => {
          // If successful, user info is now in state
          if (result.error) {
            // If there's an error (like 401), baseQueryWithReauth will handle refresh
            // and call info API automatically, so we don't need to do anything here
            console.log('getUserInfo returned error, refresh handler will manage it');
          }
        })
        .catch((err) => {
          // Silently handle errors - user might not be authenticated
          // If it's a 401, baseQueryWithReauth will handle refresh and fetch info
          console.error('Failed to fetch user info on app init:', err);
          // Reset flag on error so we can retry if needed
          hasFetchedOnMount.current = false;
        });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []); // Run only once on mount

  return (
    <HelmetProvider>
      <ConfigProvider
        theme={{
          token: {
            colorPrimary: COLOR['500'],
            borderRadius: 6,
            fontFamily: 'Lato, sans-serif',
            // Global border color for both themes
            // colorBorder: mytheme === 'dark' ? '#444444' : '#E7EAF3B2',
          },
          components: {
            Breadcrumb: {
              // linkColor: 'rgba(0,0,0,.8)',
              // itemColor: 'rgba(0,0,0,.8)',
            },
            Button: {
              colorLink: COLOR['500'],
              colorLinkActive: COLOR['700'],
              colorLinkHover: COLOR['300'],
            },
            Calendar: {
              colorBgContainer: 'none',
            },
            Card: {
              colorBorderSecondary: COLOR['borderColor'],
            },
            Carousel: {
              colorBgContainer: COLOR['800'],
              dotWidth: 8,
            },
            Form: {
              labelFontSize: 16,
            },
            Rate: {
              colorFillContent: COLOR['100'],
              colorText: COLOR['600'],
            },
            Segmented: {
              colorBgLayout: COLOR['100'],
              borderRadius: 6,
              colorTextLabel: '#000000',
            },
            Table: {
              // borderColor: COLOR['100'],
              // colorBgContainer: 'none',
              // headerBg: 'none',
              // rowHoverBg: COLOR['100'],
              // headerSortHoverBg: COLOR['50'],
              // headerSortActiveBg: COLOR['100'],
              borderColor: mytheme === 'dark' ? '#444444' : '#E7EAF3B2',
              rowHoverBg: mytheme === 'dark' ? '#262626' : COLOR['50'],
              fixedHeaderSortActiveBg:
                mytheme === 'dark' ? COLOR['300'] : COLOR['700'],
              // bodySortBg: mytheme === 'dark' ? '#1f1f1f' : '#f5f5f5',
              // Header sort
              headerSortHoverBg: mytheme === 'dark' ? '#333333' : '#e6f7ff',
              headerSortActiveBg: mytheme === 'dark' ? '#1f1f1f' : '#e6f7ff',
              // Body sorted column background
              bodySortBg: mytheme === 'dark' ? '#1f1f1f' : '#e6f7ff',
            },
            Tabs: {
              colorBorderSecondary: COLOR['100'],
            },
            Timeline: {
              dotBg: 'none',
            },
            Typography: {
              colorLink: COLOR['500'],
              colorLinkActive: COLOR['700'],
              colorLinkHover: COLOR['300'],
              linkHoverDecoration: 'underline',
            },
          },
          algorithm:
            mytheme === 'dark'
              ? antdTheme.darkAlgorithm
              : antdTheme.defaultAlgorithm,
        }}
      >
        <StylesContext.Provider
          value={{
            rowProps: {
              gutter: [
                { xs: 8, sm: 16, md: 24, lg: 32 },
                { xs: 8, sm: 16, md: 24, lg: 32 },
              ],
            },
            carouselProps: {
              autoplay: true,
              dots: true,
              dotPosition: 'bottom',
              infinite: true,
              slidesToShow: 3,
              slidesToScroll: 1,
            },
          }}
        >
          <SocketProvider>
            <ImpersonationBanner />
            <SuspendedOrgBanner />
            <RouterProvider router={routes} />
            <PermissionNotification />
          </SocketProvider>
        </StylesContext.Provider>
      </ConfigProvider>
    </HelmetProvider>
  );
}

export default App;
